#!/bin/bash

D3_SCRIPT_HOME=/data/git/D3-AUTOMATION/jmeter/ofx
JMETER_LOG_HOME=/data/tools/jmeterLogs

echo $D3_SCRIPT_HOME
rm ${JMETER_LOG_HOME}/ofxPerfRun.log
jmeter -n -t ${D3_SCRIPT_HOME}/OFX.jmx -j ${JMETER_LOG_HOME}/ofxPerfRun.log -Ljmeter.engine=DEBUG -p jmeter.config
