version: "3"
services:
  d3tests:
    build: .
    image:
      selenium_build:v1
    environment:
      - TESTNG_FILE=all_tests.xml
      - BROWSER=${BROWSER}
      - TEST_ENV=${TEST_ENV}
    volumes:
      - .:/app
    external_links:
      - zalenium
  zalenium:
    image: dosel/zalenium:3
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - ./Reports/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4444:4444
      - 5555:5555
    environment:
      - BROWSER_STACK_USER=${BROWSER_STACK_USER}
      - BROWSER_STACK_KEY=${BROWSER_STACK_KEY}
    command: >
      start --chromeContainers 1
            --firefoxContainers 0
            --maxDockerSeleniumContainers 4
            --screenWidth 1930 --screenHeight 1090
            --timeZone "America/Chicago"
            --videoRecordingEnabled false
            --sauceLabsEnabled false
            --browserStackEnabled ${BROWSER_STACK_ENABLED}
            --testingBotEnabled false
            --startTunnel true
            --seleniumImageName "elgalu/selenium:3.5"
