dist: trusty

language: java

jdk:
- oraclejdk8

branches:
  only:
  - develop
addons:
  sonarcloud:
    branches:
    - develop

before_install:
 - cp .travis_config/maven/settings.xml ~/settings.xml

install: true

script:
- cd Consumer
- export MAVEN_OPTS="-Xms2048m -Xmx3072m"
- export _JAVA_OPTIONS="-Xms2048m -Xmx3072m"
- mvn clean compile --settings ~/settings.xml sonar:sonar -Dsonar.login=${SONAR_TOKEN} -Dsonar.host.url=https://sonar.d3vcloud.com
